### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by ismarslomic** [sensu-plugins/sensu-plugins-io-checks#6]
Hi, could you please add few examples on usage of this plugin? Thanks!

**Comment by eheydrick** [comment]
I added a some usage examples with https://github.com/sensu-plugins/sensu-plugins-io-checks/commit/6f164cb200c5bfe8f4bb28fed399149cec8fc5a7. Let me know if that works and feel free to open a PR with more examples.

**Comment by ismarslomic** [comment]
@eheydrick I can´t see that **Usage** chapter is updated in https://github.com/sensu-plugins/sensu-plugins-io-checks/blob/master/README.md, only in .rb files.
